#define DFA_RULES_FILE "./lexer/dfa_states.ccsv"
#define FOLLOWS_FILE "./parser/rules/follows.txt"
#define FIRSTS_FILE "./parser/rules/firsts.txt"
#define GRAMMER_FILE "./parser/rules/grammer.txt"
#define NON_TERMINALS_FILE "./parser/rules/nonterminals.txt"